// ─── Cat Breeds ───────────────────────────────────────────────────────────────

export const CAT_BREEDS = [
  // 中国及亚洲品种
  'Chinese Domestic Cat / 中华田园猫',
  'Chinese Li Hua / 中国狸花猫',
  'Khao Manee / 泰国白猫',
  'Korat / 呵叻猫',
  'Burmese / 缅甸猫',
  'Siamese / 暹罗猫',
  'Thai / 泰国猫',
  'Singapura / 新加坡猫',
  'Japanese Bobtail / 日本短尾猫',
  // 英国 / 欧洲品种
  'British Shorthair / 英国短毛猫',
  'British Longhair / 英国长毛猫',
  'Scottish Fold / 苏格兰折耳猫',
  'Scottish Straight / 苏格兰立耳猫',
  'Persian / 波斯猫',
  'Exotic Shorthair / 异国短毛猫',
  'Himalayan / 喜马拉雅猫',
  'Russian Blue / 俄罗斯蓝猫',
  'Norwegian Forest Cat / 挪威森林猫',
  'Swedish Forest Cat / 瑞典森林猫',
  'Finnish Spitz Cat / 芬兰猫',
  'Chartreux / 沙特尔猫（法国蓝猫）',
  'Turkish Angora / 土耳其安哥拉猫',
  'Turkish Van / 土耳其梵猫',
  'Birman / 伯曼猫',
  'Devon Rex / 德文卷毛猫',
  'Cornish Rex / 柯尼斯卷毛猫',
  'Selkirk Rex / 赛尔柯克卷毛猫',
  'LaPerm / 拉波猫',
  'Manx / 马恩岛猫（无尾猫）',
  'Cymric / 威尔士猫',
  // 美国品种
  'Maine Coon / 缅因猫',
  'Ragdoll / 布偶猫',
  'American Shorthair / 美国短毛猫',
  'American Curl / 美国卷耳猫',
  'American Bobtail / 美国短尾猫',
  'Munchkin / 曼赤肯猫',
  'Bengal / 孟加拉猫',
  'Savannah / 萨凡纳猫',
  'Pixie-bob / 小精灵猫',
  'Ragamuffin / 布偶改良猫',
  // 非洲 / 中东品种
  'Abyssinian / 阿比西尼亚猫',
  'Somali / 索马里猫',
  'Egyptian Mau / 埃及猫',
  'Chausie / 沙漠猫杂交种',
  // 无毛 / 特殊品种
  'Sphynx / 斯芬克斯（无毛猫）',
  'Donskoy / 顿斯科伊（俄罗斯无毛猫）',
  'Peterbald / 彼得秃猫',
  'Lykoi / 狼人猫',
  // 其他国际品种
  'Balinese / 巴厘猫',
  'Javanese / 爪哇猫',
  'Oriental Shorthair / 东方短毛猫',
  'Oriental Longhair / 东方长毛猫',
  'Tonkinese / 东奇尼猫',
  'Ocicat / 欧西猫',
  'Bombay / 孟买猫',
  'Burmilla / 金吉拉缅甸猫',
  'Asian / 亚洲猫',
  'Tiffanie / 蒂法尼猫',
  'Nebelung / 星云猫',
  'Siberian / 西伯利亚猫',
  'Mixed Breed / 混血猫',
  'Other / 其他',
]

// ─── Cat Coat Patterns ────────────────────────────────────────────────────────

export const CAT_COAT_PATTERNS = [
  'Solid Black / 纯黑',
  'Solid White / 纯白',
  'Solid Orange/Red / 纯橘',
  'Solid Gray/Blue / 纯灰蓝',
  'Solid Cream / 纯奶油色',
  'Solid Brown / 纯棕',
  'Tabby (Brown) / 虎斑（棕）',
  'Tabby (Gray) / 虎斑（灰）',
  'Tabby (Orange) / 虎斑（橘）',
  'Tabby (Silver) / 虎斑（银色）',
  'Mackerel Tabby / 鱼骨纹虎斑',
  'Spotted Tabby / 斑点虎斑',
  'Ticked Tabby / 勾纹虎斑',
  'Calico Tabby / 彩狸（三花虎斑）',
  'Calico / 三花',
  'Tortoiseshell / 玳瑁',
  'Tuxedo (Black & White) / 奶牛（黑白）',
  'Bicolor (White + Other) / 双色（白底）',
  'Colorpoint / 重点色（暹罗纹）',
  'Lynx Point / 山猫重点色',
  'Mink / 貂色',
  'Smoke / 烟熏色',
  'Silver / 银色',
  'Golden / 金色',
  'Chinchilla / 金吉拉色',
  'Other / 其他',
]

// ─── Dog Breeds ───────────────────────────────────────────────────────────────

export const DOG_BREEDS = [
  // 中国及亚洲本土犬种
  'Chinese Pastoral Dog / 中华田园犬',
  'Tibet Mastiff / 藏獒',
  'Chow Chow / 松狮犬',
  'Chinese Shar-Pei / 沙皮犬',
  'Chongqing Dog / 重庆犬',
  'Kunming Wolfdog / 昆明狼犬',
  'Lhasa Apso / 拉萨犬',
  'Tibetan Mastiff / 藏獒',
  'Tibetan Spaniel / 西藏猎犬',
  'Tibetan Terrier / 西藏梗',
  'Shih Tzu / 西施犬',
  'Pekingese / 北京犬（京巴）',
  'Shar-Pei / 沙皮犬',
  'Shiba Inu / 柴犬',
  'Akita / 秋田犬',
  'Korean Jindo / 韩国珍岛犬',
  'Thai Ridgeback / 泰国脊背犬',
  'Basenji / 巴仙吉犬（非洲无吠犬）',
  // 牧羊犬组
  'German Shepherd / 德国牧羊犬',
  'Belgian Malinois / 比利时马犬',
  'Belgian Tervuren / 比利时特武伦犬',
  'Border Collie / 边境牧羊犬',
  'Australian Shepherd / 澳大利亚牧羊犬',
  'Australian Cattle Dog / 澳大利亚牧牛犬',
  'Collie / 柯利牧羊犬',
  'Shetland Sheepdog / 喜乐蒂牧羊犬',
  'Pembroke Welsh Corgi / 彭布罗克柯基',
  'Cardigan Welsh Corgi / 卡迪根柯基',
  'Old English Sheepdog / 英国古代牧羊犬',
  'Bouvier des Flandres / 佛兰德斯牧牛犬',
  // 工作犬组
  'Siberian Husky / 哈士奇',
  'Alaskan Malamute / 阿拉斯加雪橇犬',
  'Samoyed / 萨摩耶',
  'Doberman Pinscher / 杜宾犬',
  'Rottweiler / 罗威纳',
  'Boxer / 拳师犬',
  'Great Dane / 大丹犬',
  'Bernese Mountain Dog / 伯尼斯山地犬',
  'Saint Bernard / 圣伯纳犬',
  'Cane Corso / 卡斯罗犬',
  'Bullmastiff / 斗牛獒',
  'Newfoundland / 纽芬兰犬',
  'Leonberger / 莱昂贝格犬',
  'Great Pyrenees / 大白熊犬',
  // 运动犬组
  'Labrador Retriever / 拉布拉多',
  'Golden Retriever / 金毛寻回犬',
  'German Shorthaired Pointer / 德国短毛猎犬',
  'Cocker Spaniel / 可卡犬',
  'English Springer Spaniel / 英国史宾格犬',
  'Irish Setter / 爱尔兰雪达犬',
  'Weimaraner / 魏玛猎犬',
  'Vizsla / 维兹拉犬',
  // 猎犬组
  'Beagle / 比格犬',
  'Dachshund / 腊肠犬',
  'Greyhound / 灰猎犬',
  'Whippet / 惠比特犬',
  'Basset Hound / 巴吉度猎犬',
  'Bloodhound / 寻血猎犬',
  'Afghan Hound / 阿富汗猎犬',
  'Borzoi / 俄罗斯猎狼犬',
  'Rhodesian Ridgeback / 罗得西亚脊背犬',
  'Saluki / 萨路基猎犬',
  // 梗犬组
  'Yorkshire Terrier / 约克夏梗',
  'West Highland White Terrier / 西高地白梗',
  'Scottish Terrier / 苏格兰梗',
  'Bull Terrier / 牛头梗',
  'Miniature Schnauzer / 迷你雪纳瑞',
  'Standard Schnauzer / 标准雪纳瑞',
  'Giant Schnauzer / 巨型雪纳瑞',
  'Airedale Terrier / 万能梗',
  'Jack Russell Terrier / 杰克罗素梗',
  // 玩具犬组
  'Pomeranian / 博美犬',
  'Chihuahua / 吉娃娃',
  'Maltese / 马尔济斯',
  'Pug / 巴哥犬（哈巴狗）',
  'Cavalier King Charles Spaniel / 骑士查理王猎犬',
  'Toy Poodle / 玩具贵宾犬',
  'Papillon / 蝴蝶犬',
  'Italian Greyhound / 意大利灵缇',
  'Miniature Pinscher / 迷你杜宾',
  // 非运动犬组
  'French Bulldog / 法国斗牛犬',
  'Bulldog / 英国斗牛犬',
  'Standard Poodle / 标准贵宾犬',
  'Miniature Poodle / 迷你贵宾犬',
  'Bichon Frise / 比熊犬',
  'Dalmatian / 大麦町犬（斑点狗）',
  'Mixed Breed / 混血犬',
  'Other / 其他',
]

// ─── Dog Coat Colors ──────────────────────────────────────────────────────────

export const DOG_COAT_COLORS = [
  'Black / 黑色',
  'White / 白色',
  'Yellow / Golden / 黄色/金色',
  'Brown / Chocolate / 棕色/巧克力色',
  'Red / Orange / 红色/橙色',
  'Gray / Silver / 灰色/银色',
  'Cream / 奶油色',
  'Blue / 蓝色',
  'Black & White / 黑白',
  'Black & Tan / 黑棕',
  'Tricolor / 三色',
  'Brindle / 虎斑纹',
  'Merle / 大理石纹',
  'Spotted / 斑点',
  'Sable / 貂色',
  'Other / 其他',
]

// ─── Health Conditions ────────────────────────────────────────────────────────

export const CONDITIONS = [
  { value: 'congenital', label: 'Congenital disease / 先天性疾病' },
  { value: 'chronic', label: 'Chronic condition / 慢性病' },
  { value: 'heart', label: 'Heart disease / 心脏病' },
  { value: 'kidney', label: 'Kidney disease / 肾脏疾病' },
  { value: 'diabetes', label: 'Diabetes / 糖尿病' },
  { value: 'allergy', label: 'Allergies / 过敏' },
  { value: 'infectious', label: 'Infectious disease history / 传染病史' },
  { value: 'disability', label: 'Physical disability / 身体残疾' },
  { value: 'other_condition', label: 'Other condition / 其他病史' },
]
