// ─── Cat Breeds ───────────────────────────────────────────────────────────────

export const CAT_BREEDS = [
  // 中国及亚洲品种
  'Chinese Domestic Cat / 中华田园猫',
  'Chinese Li Hua / 中国狸花猫',
  'Khao Manee / 泰国白猫',
  'Korat / 呵叻猫',
  'Burmese / 缅甸猫',
  'Siamese / 暹罗猫',
  'Thai / 泰国猫',
  'Singapura / 新加坡猫',
  'Japanese Bobtail / 日本短尾猫',
  // 英国 / 欧洲品种
  'British Shorthair / 英国短毛猫',
  'British Longhair / 英国长毛猫',
  'Scottish Fold / 苏格兰折耳猫',
  'Scottish Straight / 苏格兰立耳猫',
  'Persian / 波斯猫',
  'Exotic Shorthair / 异国短毛猫',
  'Himalayan / 喜马拉雅猫',
  'Russian Blue / 俄罗斯蓝猫',
  'Norwegian Forest Cat / 挪威森林猫',
  'Swedish Forest Cat / 瑞典森林猫',
  'Finnish Spitz Cat / 芬兰猫',
  'Chartreux / 沙特尔猫（法国蓝猫）',
  'Turkish Angora / 土耳其安哥拉猫',
  'Turkish Van / 土耳其梵猫',
  'Birman / 伯曼猫',
  'Devon Rex / 德文卷毛猫',
  'Cornish Rex / 柯尼斯卷毛猫',
  'Selkirk Rex / 赛尔柯克卷毛猫',
  'LaPerm / 拉波猫',
  'Manx / 马恩岛猫（无尾猫）',
  'Cymric / 威尔士猫',
  // 美国品种
  'Maine Coon / 缅因猫',
  'Ragdoll / 布偶猫',
  'American Shorthair / 美国短毛猫',
  'American Curl / 美国卷耳猫',
  'American Bobtail / 美国短尾猫',
  'Munchkin / 曼赤肯猫',
  'Bengal / 孟加拉猫',
  'Savannah / 萨凡纳猫',
  'Pixie-bob / 小精灵猫',
  'Ragamuffin / 布偶改良猫',
  // 非洲 / 中东品种
  'Abyssinian / 阿比西尼亚猫',
  'Somali / 索马里猫',
  'Egyptian Mau / 埃及猫',
  'Chausie / 沙漠猫杂交种',
  // 无毛 / 特殊品种
  'Sphynx / 斯芬克斯（无毛猫）',
  'Donskoy / 顿斯科伊（俄罗斯无毛猫）',
  'Peterbald / 彼得秃猫',
  'Lykoi / 狼人猫',
  // 其他国际品种
  'Balinese / 巴厘猫',
  'Javanese / 爪哇猫',
  'Oriental Shorthair / 东方短毛猫',
  'Oriental Longhair / 东方长毛猫',
  'Tonkinese / 东奇尼猫',
  'Ocicat / 欧西猫',
  'Bombay / 孟买猫',
  'Burmilla / 金吉拉缅甸猫',
  'Asian / 亚洲猫',
  'Tiffanie / 蒂法尼猫',
  'Nebelung / 星云猫',
  'Siberian / 西伯利亚猫',
  'Mixed Breed / 混血猫',
  'Other / 其他',
]

// ─── Cat Coat Patterns ────────────────────────────────────────────────────────

export const CAT_COAT_PATTERNS = [
  'Solid Black / 纯黑',
  'Solid White / 纯白',
  'Solid Orange/Red / 纯橘',
  'Solid Gray/Blue / 纯灰蓝',
  'Solid Cream / 纯奶油色',
  'Solid Brown / 纯棕',
  'Tabby (Brown) / 虎斑（棕）',
  'Tabby (Gray) / 虎斑（灰）',
  'Tabby (Orange) / 虎斑（橘）',
  'Tabby (Silver) / 虎斑（银色）',
  'Mackerel Tabby / 鱼骨纹虎斑',
  'Spotted Tabby / 斑点虎斑',
  'Ticked Tabby / 勾纹虎斑',
  'Calico Tabby / 彩狸（三花虎斑）',
  'Calico / 三花',
  'Tortoiseshell / 玳瑁',
  'Tuxedo (Black & White) / 奶牛（黑白）',
  'Bicolor (White + Other) / 双色（白底）',
  'Colorpoint / 重点色（暹罗纹）',
  'Lynx Point / 山猫重点色',
  'Mink / 貂色',
  'Smoke / 烟熏色',
  'Silver / 银色',
  'Golden / 金色',
  'Chinchilla / 金吉拉色',
  'Other / 其他',
]

// ─── Dog Breeds ───────────────────────────────────────────────────────────────

export const DOG_BREEDS = [
  // 中国及亚洲本土犬种
  'Chinese Pastoral Dog / 中华田园犬',
  'Tibet Mastiff / 藏獒',
  'Chow Chow / 松狮犬',
  'Chinese Shar-Pei / 沙皮犬',
  'Chongqing Dog / 重庆犬',
  'Kunming Wolfdog / 昆明狼犬',
  'Lhasa Apso / 拉萨犬',
  'Tibetan Mastiff / 藏獒',
  'Tibetan Spaniel / 西藏猎犬',
  'Tibetan Terrier / 西藏梗',
  'Shih Tzu / 西施犬',
  'Pekingese / 北京犬（京巴）',
  'Shar-Pei / 沙皮犬',
  'Shiba Inu / 柴犬',
  'Akita / 秋田犬',
  'Korean Jindo / 韩国珍岛犬',
  'Thai Ridgeback / 泰国脊背犬',
  'Basenji / 巴仙吉犬（非洲无吠犬）',
  // 牧羊犬组
  'German Shepherd / 德国牧羊犬',
  'Belgian Malinois / 比利时马犬',
  'Belgian Tervuren / 比利时特武伦犬',
  'Border Collie / 边境牧羊犬',
  'Australian Shepherd / 澳大利亚牧羊犬',
  'Australian Cattle Dog / 澳大利亚牧牛犬',
  'Collie / 柯利牧羊犬',
  'Shetland Sheepdog / 喜乐蒂牧羊犬',
  'Pembroke Welsh Corgi / 彭布罗克柯基',
  'Cardigan Welsh Corgi / 卡迪根柯基',
  'Old English Sheepdog / 英国古代牧羊犬',
  'Bouvier des Flandres / 佛兰德斯牧牛犬',
  // 工作犬组
  'Siberian Husky / 哈士奇',
  'Alaskan Malamute / 阿拉斯加雪橇犬',
  'Samoyed / 萨摩耶',
  'Doberman Pinscher / 杜宾犬',
  'Rottweiler / 罗威纳',
  'Boxer / 拳师犬',
  'Great Dane / 大丹犬',
  'Bernese Mountain Dog / 伯尼斯山地犬',
  'Saint Bernard / 圣伯纳犬',
  'Cane Corso / 卡斯罗犬',
  'Bullmastiff / 斗牛獒',
  'Newfoundland / 纽芬兰犬',
  'Leonberger / 莱昂贝格犬',
  'Great Pyrenees / 大白熊犬',
  // 运动犬组
  'Labrador Retriever / 拉布拉多',
  'Golden Retriever / 金毛寻回犬',
  'German Shorthaired Pointer / 德国短毛猎犬',
  'Cocker Spaniel / 可卡犬',
  'English Springer Spaniel / 英国史宾格犬',
  'Irish Setter / 爱尔兰雪达犬',
  'Weimaraner / 魏玛猎犬',
  'Vizsla / 维兹拉犬',
  // 猎犬组
  'Beagle / 比格犬',
  'Dachshund / 腊肠犬',
  'Greyhound / 灰猎犬',
  'Whippet / 惠比特犬',
  'Basset Hound / 巴吉度猎犬',
  'Bloodhound / 寻血猎犬',
  'Afghan Hound / 阿富汗猎犬',
  'Borzoi / 俄罗斯猎狼犬',
  'Rhodesian Ridgeback / 罗得西亚脊背犬',
  'Saluki / 萨路基猎犬',
  // 梗犬组
  'Yorkshire Terrier / 约克夏梗',
  'West Highland White Terrier / 西高地白梗',
  'Scottish Terrier / 苏格兰梗',
  'Bull Terrier / 牛头梗',
  'Miniature Schnauzer / 迷你雪纳瑞',
  'Standard Schnauzer / 标准雪纳瑞',
  'Giant Schnauzer / 巨型雪纳瑞',
  'Airedale Terrier / 万能梗',
  'Jack Russell Terrier / 杰克罗素梗',
  // 玩具犬组
  'Pomeranian / 博美犬',
  'Chihuahua / 吉娃娃',
  'Maltese / 马尔济斯',
  'Pug / 巴哥犬（哈巴狗）',
  'Cavalier King Charles Spaniel / 骑士查理王猎犬',
  'Toy Poodle / 玩具贵宾犬',
  'Papillon / 蝴蝶犬',
  'Italian Greyhound / 意大利灵缇',
  'Miniature Pinscher / 迷你杜宾',
  // 非运动犬组
  'French Bulldog / 法国斗牛犬',
  'Bulldog / 英国斗牛犬',
  'Standard Poodle / 标准贵宾犬',
  'Miniature Poodle / 迷你贵宾犬',
  'Bichon Frise / 比熊犬',
  'Dalmatian / 大麦町犬（斑点狗）',
  'Mixed Breed / 混血犬',
  'Other / 其他',
]

// ─── Dog Coat Colors ──────────────────────────────────────────────────────────

export const DOG_COAT_COLORS = [
  'Black / 黑色',
  'White / 白色',
  'Yellow / Golden / 黄色/金色',
  'Brown / Chocolate / 棕色/巧克力色',
  'Red / Orange / 红色/橙色',
  'Gray / Silver / 灰色/银色',
  'Cream / 奶油色',
  'Blue / 蓝色',
  'Black & White / 黑白',
  'Black & Tan / 黑棕',
  'Tricolor / 三色',
  'Brindle / 虎斑纹',
  'Merle / 大理石纹',
  'Spotted / 斑点',
  'Sable / 貂色',
  'Other / 其他',
]

// ─── Exotic Pet Species Config ────────────────────────────────────────────────

export type SpeciesKey = 'CAT' | 'DOG' | 'RABBIT' | 'HAMSTER' | 'CHINCHILLA' | 'GUINEA_PIG' | 'FERRET' | 'PARROT' | 'BIRD' | 'SNAKE' | 'LIZARD' | 'TURTLE' | 'HEDGEHOG' | 'SUGAR_GLIDER' | 'SPIDER' | 'SCORPION' | 'CRAB'

// v2: specialPeriods + hibernationMonths added to all species
export type SpecialPeriodKey = 'PRE_SHEDDING' | 'SHEDDING' | 'HIBERNATION' | 'MOLTING' | 'BREEDING'

export const SPECIAL_PERIOD_LABELS: Record<SpecialPeriodKey, string> = {
  PRE_SHEDDING: '蜕皮前期',
  SHEDDING: '蜕皮中',
  HIBERNATION: '冬眠期',
  MOLTING: '换羽/换毛期',
  BREEDING: '繁殖季',
}

export const SPECIES_CONFIG: Record<SpeciesKey, {
  icon: string
  label: string
  showLitter: boolean
  litterLabel: string
  showWalk: boolean
  walkLabel: string
  showShedding: boolean
  showFeedingItem: boolean
  feedingItems: string[]
  waterMode: 'measure' | 'bowl' | 'none'
  specialPeriods: SpecialPeriodKey[]
  hibernationMonths: number[]
  breeds: string[]
  coatOptions: string[]
}> = {
  CAT: {
    icon: '🐱', label: '猫',
    showLitter: true, litterLabel: '如厕次数',
    showWalk: false, walkLabel: '',
    showShedding: false, showFeedingItem: false, feedingItems: [],
    waterMode: 'measure',
    specialPeriods: ['BREEDING'], hibernationMonths: [],
    breeds: [], coatOptions: [],
  },
  DOG: {
    icon: '🐶', label: '狗',
    showLitter: false, litterLabel: '',
    showWalk: true, walkLabel: '散步时长（分钟）',
    showShedding: false, showFeedingItem: false, feedingItems: [],
    waterMode: 'measure',
    specialPeriods: ['BREEDING'], hibernationMonths: [],
    breeds: [], coatOptions: [],
  },
  RABBIT: {
    icon: '🐰', label: '兔子',
    showLitter: true, litterLabel: '排便次数',
    showWalk: true, walkLabel: '活动时长（分钟）',
    showShedding: false, showFeedingItem: false, feedingItems: [],
    waterMode: 'measure',
    specialPeriods: ['BREEDING'], hibernationMonths: [],
    breeds: [
      '垂耳兔 / Holland Lop', '迷你垂耳兔 / Mini Lop', '英国垂耳兔 / English Lop',
      '荷兰兔 / Dutch', '侏儒兔 / Netherland Dwarf', '狮子兔 / Lionhead',
      '安哥拉兔 / Angora', '雷克斯兔 / Rex', '新西兰兔 / New Zealand',
      '比利时兔 / Flemish Giant', '田园兔 / Mixed',
    ],
    coatOptions: ['纯白', '纯黑', '灰色', '棕色', '橙色', '奶牛色（黑白）', '三花', '渐变色'],
  },
  HAMSTER: {
    icon: '🐹', label: '仓鼠',
    showLitter: true, litterLabel: '排便次数',
    showWalk: false, walkLabel: '',
    showShedding: false, showFeedingItem: false, feedingItems: [],
    waterMode: 'measure',
    specialPeriods: ['HIBERNATION', 'BREEDING'], hibernationMonths: [10, 11, 12, 1, 2],
    breeds: [
      '黄金仓鼠 / Syrian Hamster', '加卡利亚仓鼠 / Djungarian / Winter White',
      '坎培尔仓鼠 / Campbell\'s Dwarf', '罗伯罗夫斯基仓鼠 / Roborovski',
      '中国仓鼠 / Chinese Hamster',
    ],
    coatOptions: ['黄金色', '白色', '灰色', '棕色', '奶油色', '花色（杂色）'],
  },
  CHINCHILLA: {
    icon: '🐭', label: '龙猫',
    showLitter: true, litterLabel: '排便次数',
    showWalk: true, walkLabel: '放风时长（分钟）',
    showShedding: false, showFeedingItem: false, feedingItems: [],
    waterMode: 'measure',
    specialPeriods: ['BREEDING'], hibernationMonths: [],
    breeds: ['标准灰 / Standard Gray', '白色 / White', '米色 / Beige', '黑色天鹅绒 / Black Velvet', '紫罗兰 / Violet', '蓝宝石 / Sapphire'],
    coatOptions: ['标准灰', '白色', '米色', '黑色天鹅绒', '紫罗兰', '蓝宝石'],
  },
  GUINEA_PIG: {
    icon: '🐾', label: '豚鼠',
    showLitter: true, litterLabel: '排便次数',
    showWalk: true, walkLabel: '活动时长（分钟）',
    showShedding: false, showFeedingItem: false, feedingItems: [],
    waterMode: 'measure',
    specialPeriods: ['BREEDING'], hibernationMonths: [],
    breeds: [
      '英国短毛豚鼠 / American', '秘鲁长毛豚鼠 / Peruvian', '阿比西尼亚豚鼠 / Abyssinian',
      '泰迪豚鼠 / Teddy', '无毛豚鼠 / Skinny', '冠毛豚鼠 / Crested',
    ],
    coatOptions: ['纯白', '纯黑', '棕色', '橙色', '奶油色', '双色', '三花'],
  },
  FERRET: {
    icon: '🦡', label: '雪貂',
    showLitter: true, litterLabel: '如厕次数',
    showWalk: true, walkLabel: '活动时长（分钟）',
    showShedding: false, showFeedingItem: false, feedingItems: [],
    waterMode: 'measure',
    specialPeriods: ['BREEDING', 'MOLTING'], hibernationMonths: [],
    breeds: ['宠物雪貂 / Domestic Ferret', '安哥拉雪貂 / Angora Ferret'],
    coatOptions: ['白化（白色）', '深褐色', '银色', '黑色', '肉桂色', '巧克力色', '花斑'],
  },
  PARROT: {
    icon: '🦜', label: '鹦鹉',
    showLitter: false, litterLabel: '',
    showWalk: false, walkLabel: '',
    showShedding: false, showFeedingItem: false, feedingItems: [],
    waterMode: 'bowl',
    specialPeriods: ['MOLTING', 'BREEDING'], hibernationMonths: [],
    breeds: [
      '虎皮鹦鹉 / Budgerigar', '玄凤鹦鹉 / Cockatiel', '牡丹鹦鹉 / Lovebird',
      '和尚鹦鹉 / Monk Parakeet', '太平洋鹦鹉 / Pacific Parrotlet',
      '非洲灰鹦鹉 / African Grey', '亚马逊鹦鹉 / Amazon Parrot',
      '葵花凤头鹦鹉 / Cockatoo', '金刚鹦鹉 / Macaw', '折衷鹦鹉 / Eclectus',
    ],
    coatOptions: ['绿色', '蓝色', '黄色', '红色', '白色', '灰色', '彩色杂羽'],
  },
  BIRD: {
    icon: '🐦', label: '鸟类',
    showLitter: false, litterLabel: '',
    showWalk: false, walkLabel: '',
    showShedding: false, showFeedingItem: false, feedingItems: [],
    waterMode: 'bowl',
    specialPeriods: ['MOLTING', 'BREEDING'], hibernationMonths: [],
    breeds: [
      '金丝雀 / Canary', '斑胸草雀 / Zebra Finch', '文鸟 / Java Sparrow',
      '十姐妹 / Society Finch', '芙蓉鸟 / Red Factor Canary', '其他 / Other',
    ],
    coatOptions: ['黄色', '红色', '白色', '灰色', '棕色', '花色'],
  },
  SNAKE: {
    icon: '🐍', label: '蛇',
    showLitter: false, litterLabel: '',
    showWalk: true, walkLabel: '盘出时长（分钟）',
    showShedding: true, showFeedingItem: true,
    feedingItems: ['乳鼠', '小鼠', '中鼠', '大鼠', '超大鼠', '小兔子', '冷冻食材', '活体食材'],
    waterMode: 'bowl',
    specialPeriods: ['PRE_SHEDDING', 'SHEDDING', 'BREEDING'], hibernationMonths: [],
    breeds: [
      '球蟒 / Ball Python', '玉米蛇 / Corn Snake', '奶蛇 / Milk Snake',
      '加州王蛇 / California Kingsnake', '蓝眼琉璃蟒 / Blue-Eyed Leucistic',
      '网纹蟒 / Reticulated Python', '绿树蟒 / Green Tree Python',
      '翠青蛇 / Smooth Green Snake', '虎纹游蛇 / Tiger Keelback',
      '其他 / Other',
    ],
    coatOptions: ['野生色', '白化', '白球', '蜘蛛花纹', '香蕉色', '迷彩', '丛林色', '幽灵色', '黄油色', '其他'],
  },
  LIZARD: {
    icon: '🦎', label: '蜥蜴/守宫',
    showLitter: false, litterLabel: '',
    showWalk: true, walkLabel: '活动时长（分钟）',
    showShedding: true, showFeedingItem: true,
    feedingItems: ['蟋蟀', '杜比亚蟑螂', '面包虫', '麦皮虫', '黑水虻幼虫', '蔬菜叶', '水果', 'CGD专用粉', '综合'],
    waterMode: 'bowl',
    specialPeriods: ['PRE_SHEDDING', 'SHEDDING', 'HIBERNATION', 'BREEDING'], hibernationMonths: [11, 12, 1, 2],
    breeds: [
      '鬃狮蜥 / Bearded Dragon', '豹纹守宫 / Leopard Gecko',
      '睫角守宫 / Crested Gecko', '绿鬣蜥 / Green Iguana',
      '蓝舌蜥 / Blue-Tongued Skink', '变色龙 / Veiled Chameleon',
      '中部蓝舌蜥 / Central BTS', '飞蜥 / Flying Lizard',
      '安乐蜥 / Anole', '其他 / Other',
    ],
    coatOptions: ['野生色', '白化', '超雪（Super Snow）', '暴风雪（Blizzard）', '高黄', '杂色', '幻彩', '其他'],
  },
  TURTLE: {
    icon: '🐢', label: '龟类',
    showLitter: false, litterLabel: '',
    showWalk: true, walkLabel: '活动/泡澡时长（分钟）',
    showShedding: true, showFeedingItem: true,
    feedingItems: ['专用龟粮', '蔬菜（生菜/苦菊）', '水果（适量）', '虾/鱼肉', '综合'],
    waterMode: 'bowl',
    specialPeriods: ['PRE_SHEDDING', 'SHEDDING', 'HIBERNATION'], hibernationMonths: [10, 11, 12, 1, 2],
    breeds: [
      '苏卡达陆龟 / Sulcata Tortoise', '赫曼陆龟 / Hermann\'s Tortoise',
      '豹纹陆龟 / Leopard Tortoise', '印度星龟 / Indian Star Tortoise',
      '缘翘陆龟 / Marginated Tortoise', '黑靴陆龟 / Black Spurred Tortoise',
      '巴西龟（红耳龟）/ Red-Eared Slider', '黄喉拟水龟 / Yellow-Throated Pond Turtle',
      '地图龟 / Map Turtle', '闭壳龟 / Box Turtle', '其他 / Other',
    ],
    coatOptions: ['标准色', '白化', '高橙', '黑化', '白化高橙', '其他'],
  },
  HEDGEHOG: {
    icon: '🦔', label: '刺猬',
    showLitter: true, litterLabel: '排便次数',
    showWalk: true, walkLabel: '滚轮/活动时长（分钟）',
    showShedding: false, showFeedingItem: true,
    feedingItems: ['刺猬专用粮', '优质猫粮（低脂）', '蟋蟀/面包虫', '蔬菜水果（少量）', '综合'],
    waterMode: 'measure',
    specialPeriods: ['HIBERNATION', 'BREEDING'], hibernationMonths: [10, 11, 12, 1, 2],
    breeds: [
      '非洲侏儒刺猬 / African Pygmy Hedgehog',
      '欧洲刺猬 / European Hedgehog',
      '长耳刺猬 / Long-Eared Hedgehog',
    ],
    coatOptions: ['盐和胡椒（标准）', '白化', '纯白', '巧克力色', '奶油色', '苹果馅饼色', '灰色', '棕色'],
  },
  SUGAR_GLIDER: {
    icon: '🐿️', label: '蜜袋鼯',
    showLitter: false, litterLabel: '',
    showWalk: true, walkLabel: '活动时长（分钟）',
    showShedding: false, showFeedingItem: true,
    feedingItems: ['BML食谱', '专用蜜袋鼯粮', '新鲜水果', '蜂蜜水', '蟋蟀/昆虫'],
    waterMode: 'bowl',
    specialPeriods: ['BREEDING'], hibernationMonths: [],
    breeds: [
      '普通蜜袋鼯 / Classic Gray Sugar Glider',
      '白化蜜袋鼯 / Albino Sugar Glider',
      '亮化蜜袋鼯 / Leucistic Sugar Glider',
      '棉花糖蜜袋鼯 / Creamino Sugar Glider',
    ],
    coatOptions: ['经典灰', '白化', '亮化（白色）', '棉花糖色（奶黄）', '金色', '黑化', '其他'],
  },
  SPIDER: {
    icon: '🕷️', label: '蜘蛛/狼蛛',
    showLitter: false, litterLabel: '',
    showWalk: false, walkLabel: '',
    showShedding: true, showFeedingItem: true,
    feedingItems: ['蟋蟀', '杜比亚蟑螂', '面包虫', '麦皮虫'],
    waterMode: 'none',
    specialPeriods: ['PRE_SHEDDING', 'SHEDDING'], hibernationMonths: [],
    breeds: [
      '墨西哥红膝蜘蛛 / Mexican Red Knee', '智利玫瑰红蜘蛛 / Chilean Rose Hair',
      '蓝宝石华丽雨林蜘蛛 / Gooty Sapphire', '粉红脚蜘蛛 / Pink Toe Tarantula',
      '橙色巴布蜘蛛 / Orange Baboon Tarantula', '绿瓶蓝蜘蛛 / Green Bottle Blue',
      '红火玫瑰蜘蛛 / Chilean Flame Tarantula', '其他 / Other',
    ],
    coatOptions: ['棕色系', '黑色系', '蓝色系', '橙色系', '彩色杂纹', '其他'],
  },
  SCORPION: {
    icon: '🦂', label: '蝎子',
    showLitter: false, litterLabel: '',
    showWalk: false, walkLabel: '',
    showShedding: true, showFeedingItem: true,
    feedingItems: ['蟋蟀', '杜比亚蟑螂', '面包虫', '乳鼠（帝王蝎适用）'],
    waterMode: 'none',
    specialPeriods: ['PRE_SHEDDING', 'SHEDDING'], hibernationMonths: [],
    breeds: [
      '帝王蝎 / Emperor Scorpion', '亚洲森林蝎 / Asian Forest Scorpion',
      '红爪蝎 / Red Claw Scorpion', '沙漠金蝎 / Desert Hairy Scorpion',
      '扁石蝎 / Flat Rock Scorpion', '其他 / Other',
    ],
    coatOptions: ['黑色', '深棕色', '棕色', '黄棕色', '黄色', '其他'],
  },
  CRAB: {
    icon: '🦀', label: '寄居蟹/螃蟹',
    showLitter: false, litterLabel: '',
    showWalk: true, walkLabel: '活动时长（分钟）',
    showShedding: true, showFeedingItem: true,
    feedingItems: ['商业寄居蟹粮', '新鲜水果', '蔬菜', '鱼虾（蛋白质）', '椰子'],
    waterMode: 'bowl',
    specialPeriods: ['SHEDDING'], hibernationMonths: [],
    breeds: [
      '陆寄居蟹 / Land Hermit Crab', '椰子蟹 / Coconut Crab',
      '招潮蟹 / Fiddler Crab', '地蟹 / Land Crab',
      '其他 / Other',
    ],
    coatOptions: ['红色系', '蓝色系', '棕色系', '橙色系', '紫色系', '杂色'],
  },
}

export const ALL_SPECIES = Object.entries(SPECIES_CONFIG).map(([key, cfg]) => ({
  value: key as SpeciesKey,
  icon: cfg.icon,
  label: cfg.label,
}))

// ─── Activity Checkin Config ─────────────────────────────────────────────────

export const ACTIVITY_CONFIG: Record<SpeciesKey, { key: string; icon: string; label: string }[]> = {
  CAT: [
    { key: 'play', icon: '🎾', label: '互动玩耍' },
    { key: 'groom', icon: '🪮', label: '梳毛' },
    { key: 'sunbathe', icon: '☀️', label: '晒太阳' },
    { key: 'cuddle', icon: '🤗', label: '抱抱撸猫' },
  ],
  DOG: [
    { key: 'walk', icon: '🦮', label: '遛弯散步' },
    { key: 'play', icon: '🎾', label: '互动玩耍' },
    { key: 'groom', icon: '🪮', label: '梳毛洗澡' },
    { key: 'train', icon: '🏅', label: '训练互动' },
  ],
  RABBIT: [
    { key: 'play', icon: '🎾', label: '自由活动' },
    { key: 'groom', icon: '🪮', label: '梳毛' },
    { key: 'veggie', icon: '🥬', label: '喂蔬菜零食' },
    { key: 'cuddle', icon: '🤗', label: '互动抚摸' },
  ],
  HAMSTER: [
    { key: 'wheel', icon: '🎡', label: '滚轮跑步' },
    { key: 'explore', icon: '🔍', label: '探索活动' },
    { key: 'snack', icon: '🌻', label: '喂零食' },
    { key: 'clean', icon: '🧹', label: '清洁笼舍' },
  ],
  CHINCHILLA: [
    { key: 'dustbath', icon: '🪨', label: '沙浴' },
    { key: 'play', icon: '🎾', label: '放风玩耍' },
    { key: 'groom', icon: '🪮', label: '梳毛' },
    { key: 'cuddle', icon: '🤗', label: '互动抚摸' },
  ],
  GUINEA_PIG: [
    { key: 'play', icon: '🎾', label: '自由活动' },
    { key: 'veggie', icon: '🥬', label: '喂蔬菜' },
    { key: 'groom', icon: '🪮', label: '梳毛' },
    { key: 'cuddle', icon: '🤗', label: '互动抚摸' },
  ],
  FERRET: [
    { key: 'play', icon: '🎾', label: '玩耍探索' },
    { key: 'tunnel', icon: '🕳️', label: '隧道游戏' },
    { key: 'groom', icon: '🪮', label: '梳毛洗澡' },
    { key: 'cuddle', icon: '🤗', label: '互动抚摸' },
  ],
  PARROT: [
    { key: 'talk', icon: '🗣️', label: '语言互动' },
    { key: 'trick', icon: '🎪', label: '训练技巧' },
    { key: 'flight', icon: '✈️', label: '放飞活动' },
    { key: 'foraging', icon: '🌿', label: '觅食游戏' },
  ],
  BIRD: [
    { key: 'sing', icon: '🎵', label: '唱歌互动' },
    { key: 'flight', icon: '✈️', label: '放飞活动' },
    { key: 'forage', icon: '🌿', label: '觅食游戏' },
    { key: 'bath', icon: '🚿', label: '水浴' },
  ],
  SNAKE: [
    { key: 'explore', icon: '🔍', label: '放风探索' },
    { key: 'soak', icon: '🛁', label: '温水泡浴' },
    { key: 'handle', icon: '🤝', label: '上手互动' },
    { key: 'clean', icon: '🧹', label: '清洁笼舍' },
  ],
  LIZARD: [
    { key: 'sunbathe', icon: '☀️', label: '晒灯basking' },
    { key: 'explore', icon: '🔍', label: '放风探索' },
    { key: 'handle', icon: '🤝', label: '上手互动' },
    { key: 'clean', icon: '🧹', label: '清洁笼舍' },
  ],
  TURTLE: [
    { key: 'swim', icon: '🏊', label: '游泳活动' },
    { key: 'sunbathe', icon: '☀️', label: '晒背晒灯' },
    { key: 'explore', icon: '🔍', label: '陆地探索' },
    { key: 'clean', icon: '🧹', label: '换水清洁' },
  ],
  HEDGEHOG: [
    { key: 'wheel', icon: '🎡', label: '滚轮跑步' },
    { key: 'explore', icon: '🔍', label: '放风探索' },
    { key: 'bath', icon: '🚿', label: '泡脚洗澡' },
    { key: 'cuddle', icon: '🤗', label: '上手互动' },
  ],
  SUGAR_GLIDER: [
    { key: 'glide', icon: '🪂', label: '滑翔飞行' },
    { key: 'bonding', icon: '❤️', label: '亲子bonding' },
    { key: 'play', icon: '🎾', label: '玩耍互动' },
    { key: 'snack', icon: '🍑', label: '喂零食' },
  ],
  SPIDER: [
    { key: 'feed', icon: '🦗', label: '喂食' },
    { key: 'observe', icon: '👁️', label: '观察行为' },
    { key: 'clean', icon: '🧹', label: '清洁笼舍' },
    { key: 'photo', icon: '📸', label: '记录拍照' },
  ],
  SCORPION: [
    { key: 'feed', icon: '🦗', label: '喂食' },
    { key: 'observe', icon: '👁️', label: '观察行为' },
    { key: 'clean', icon: '🧹', label: '清洁笼舍' },
    { key: 'photo', icon: '📸', label: '记录拍照' },
  ],
  CRAB: [
    { key: 'swim', icon: '🏊', label: '游泳活动' },
    { key: 'feed', icon: '🦐', label: '喂食' },
    { key: 'clean', icon: '🧹', label: '换水清洁' },
    { key: 'observe', icon: '👁️', label: '观察行为' },
  ],
}

// ─── Health Conditions ────────────────────────────────────────────────────────

export const CONDITIONS = [
  { value: 'congenital', label: 'Congenital disease / 先天性疾病' },
  { value: 'chronic', label: 'Chronic condition / 慢性病' },
  { value: 'heart', label: 'Heart disease / 心脏病' },
  { value: 'kidney', label: 'Kidney disease / 肾脏疾病' },
  { value: 'diabetes', label: 'Diabetes / 糖尿病' },
  { value: 'allergy', label: 'Allergies / 过敏' },
  { value: 'infectious', label: 'Infectious disease history / 传染病史' },
  { value: 'disability', label: 'Physical disability / 身体残疾' },
  { value: 'other_condition', label: 'Other condition / 其他病史' },
]
